### ISSUE TITLE
TS 5.0 module conversion will require changing how internal types are obtained

### ISSUE THREAD

**Issue by jakebailey** [nonara/ts-expose-internals#10]
https://github.com/microsoft/TypeScript/pull/51387 majorly changes how TypeScript is built and packaged.

One thing that differs is that disabling `stripInternal` is no longer the way to obtain our internal API.

Instead, running the `dts` task in our repo will produce these files:

```
-rw-r--r-- 1 jabaile jabaile 635K Nov  3 13:45 tsserverlibrary.d.ts
-rw-r--r-- 1 jabaile jabaile 1.5M Nov  3 13:45 tsserverlibrary.internal.d.ts
-rw-r--r-- 1 jabaile jabaile 466K Nov  3 13:45 typescript.d.ts
-rw-r--r-- 1 jabaile jabaile 1.3M Nov  3 13:45 typescript.internal.d.ts
```

You should be able to rename and ship the `.internal.d.ts` files for this package. I believe this will also mean you can drop all of your post-build patches; the internal API d.ts files are now checked in our tests so should contain a type-complete set of exports.

**Comment by nonara** [comment]
Hi Jake! Thanks for the heads up. That had to be some work to do! Looking forward to taking a look at how you implemented it.

Sounds like this would be a good opportunity to do my rewrite to rely on GitHub CI + artifacts. Do you guys have an idea of when 5 will ship?

**Comment by jakebailey** [comment]
You can check https://github.com/microsoft/TypeScript/issues/51362 for the schedule; stable would be in March.

This probably affects you less than `byots` given it's nightly and broken; I posted this same issue there.

**Comment by jackTabsCode** [comment]
@nonara Hello, curious if there's any update on this? We're currently at stable release with 5.0

**Comment by nonara** [comment]
@jackTabsCode I'm expecting to have this done by early next week. Finishing up major ts-patch rewrite at the moment

**Comment by osyrisrblx** [comment]
@nonara Hi 👋, any updates on this? My project depends on ts-expose-internals and we're blocked on upgrading to TS 5.0.

**Comment by nonara** [comment]
@osyrisrblx Understood! I've been slammed for months, but I've blocked out the foreseeable to get caught up on OSS. 

I'm wrapping tests for the new ts-patch and then I'll be redoing this right after.

If all goes well, new tsei should be live next week.

**Comment by nonara** [comment]
New version is live + all >=v5 types are published! If anyone faces any issues, let me know.

I rewrote everything to run entirely in GitHub Actions. It also has much smoother handling and retries for build failures.
