### ISSUE TITLE
TypeScript 4.2

### ISSUE THREAD

**Issue by kevinramharak** [nonara/ts-expose-internals#4]
Typescript 4.2 has been out for a few days. Any chance for an npm release?
https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/

**Comment by nonara** [comment]
Thanks for bringing this to my attention! Looks like the TS team added some tags for backdated versions on github that were too old to build properly, so it was failing. To top it off, somehow my server email notifications account broke down, so I wasn't getting any failure emails!

I've added the broken versions to the skip list and ran it through, and everything built fine. Versions 4.2.x are now available.
