### ISSUE TITLE
Typescript 4.7.0-beta

### ISSUE THREAD

**Issue by Dionysusnu** [nonara/ts-expose-internals#8]
TS 4.7.0-beta was released 36 hours ago. Previous betas and RCs got versions. As per the readme, the 12-hourly script should have picked it up by now, but the latest release is still 4.6.0-beta.

**Comment by nonara** [comment]
Hi. Thanks for the report!

Looks like they haven't updated the git tags yet. Occasionally they forget to do that for a little while. Our scanner builds from source, so it checks for new versions by scanning version tags in the repository.

Maybe give them a nudge on Twitter or Discord to see if they'll push the latest beta tag. In the mean time, you can usually get by using the latest release until they get it synced up, but if there is something missing, you can probably use `byots` (linked in our readme) until they get it caught up.

**Comment by nonara** [comment]
It seems my API keys on NPM got wiped out, so versions weren't publishing after all!

This is corrected now, and we're up to date. New versions should properly publish.
