### ISSUE TITLE
TypeScript 4.7.2

### ISSUE THREAD

**Issue by osyrisrblx** [nonara/ts-expose-internals#9]
Looks like a new build hasn't been generated yet.. maybe the script is stuck?

**Comment by nonara** [comment]
Thanks for the report! The server upgraded to a new `git`, which affected our scripts. They had a syntax requirement change. I've updated the server's launch script and it's working again! 4.7.2 is published.

**Comment by osyrisrblx** [comment]
Thanks @nonara!! This project is super useful for https://roblox-ts.com/

**Comment by nonara** [comment]
Glad to hear it! Nice work, by the way! Looks like a cool project.
